"""empty message

Revision ID: 098cbc9fc332
Revises: 340118beb9e1
Create Date: 2025-08-11 14:45:52.105355

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '098cbc9fc332'
down_revision = '340118beb9e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bet', schema=None) as batch_op:
        batch_op.add_column(sa.Column('competition_code', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('external_match_id', sa.Integer(), nullable=True))

    with op.batch_alter_table('bet_option', schema=None) as batch_op:
        batch_op.add_column(sa.Column('external_team_id', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bet_option', schema=None) as batch_op:
        batch_op.drop_column('external_team_id')

    with op.batch_alter_table('bet', schema=None) as batch_op:
        batch_op.drop_column('external_match_id')
        batch_op.drop_column('competition_code')

    # ### end Alembic commands ###
