"""empty message

Revision ID: 340118beb9e1
Revises: a3626b592bdd
Create Date: 2025-08-11 12:05:49.444400

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '340118beb9e1'
down_revision = 'a3626b592bdd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bet', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('playground_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_constraint('bet_user_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('bet_playground_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'playground', ['playground_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bet', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('bet_playground_id_fkey', 'playground', ['playground_id'], ['id'])
        batch_op.create_foreign_key('bet_user_id_fkey', 'user', ['user_id'], ['id'])
        batch_op.alter_column('playground_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
