"""empty message

Revision ID: 346ca14ea3bb
Revises: 
Create Date: 2025-07-31 17:05:23.044795

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '346ca14ea3bb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_bet', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bet_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'bet', ['bet_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_bet', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('bet_id')

    # ### end Alembic commands ###
