"""empty message

Revision ID: 7466e1574cc3
Revises: 3e8a726dd642
Create Date: 2025-08-05 11:10:38.104530

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7466e1574cc3'
down_revision = '3e8a726dd642'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bet', schema=None) as batch_op:
        batch_op.add_column(sa.Column('event_description', sa.String(length=100), nullable=True))
        batch_op.drop_column('event_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bet', schema=None) as batch_op:
        batch_op.add_column(sa.Column('event_id', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.drop_column('event_description')

    # ### end Alembic commands ###
