"""empty message

Revision ID: 780a9dfdeb92
Revises: f5cc45146c86
Create Date: 2025-08-11 11:35:04.522906

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '780a9dfdeb92'
down_revision = 'f5cc45146c86'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_bet', schema=None) as batch_op:
        batch_op.add_column(sa.Column('option_id', sa.Integer(), nullable=False))
        batch_op.alter_column('bet_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.create_unique_constraint('unique_user_bet_vote', ['user_id', 'bet_id'])
        batch_op.create_foreign_key(None, 'bet', ['bet_id'], ['id'])
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])
        batch_op.create_foreign_key(None, 'bet_option', ['option_id'], ['id'])
        batch_op.drop_column('bet_option_name')
        batch_op.drop_column('bet_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_bet', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bet_name', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('bet_option_name', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint('unique_user_bet_vote', type_='unique')
        batch_op.alter_column('bet_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_column('option_id')

    # ### end Alembic commands ###
