"""empty message

Revision ID: 8c1c5dd14994
Revises: 
Create Date: 2025-08-06 11:05:09.417302

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c1c5dd14994'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bet', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type', sa.Enum('sports', 'others', name='bettype'), nullable=False))
        batch_op.add_column(sa.Column('event_description', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('resolved_at', sa.DateTime(), nullable=True))
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=250),
               type_=sa.Enum('pending', 'active', 'locked', 'resolved', 'cancelled', name='betstatus'),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bet', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.Enum('pending', 'active', 'locked', 'resolved', 'cancelled', name='betstatus'),
               type_=sa.VARCHAR(length=250),
               nullable=True)
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
        batch_op.drop_column('resolved_at')
        batch_op.drop_column('event_description')
        batch_op.drop_column('type')

    # ### end Alembic commands ###
