"""empty message

Revision ID: a3626b592bdd
Revises: 780a9dfdeb92
Create Date: 2025-08-11 12:01:15.031471

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a3626b592bdd'
down_revision = '780a9dfdeb92'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bet', schema=None) as batch_op:
        batch_op.add_column(sa.Column('winner_option_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'bet_option', ['winner_option_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bet', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('winner_option_id')

    # ### end Alembic commands ###
