"""empty message

Revision ID: c4aeed7515db
Revises: 
Create Date: 2025-08-17 11:39:50.869948

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c4aeed7515db'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bet', schema=None) as batch_op:
        batch_op.add_column(sa.Column('league', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('match', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bet', schema=None) as batch_op:
        batch_op.drop_column('match')
        batch_op.drop_column('league')

    # ### end Alembic commands ###
