"""empty message

Revision ID: ccb8b01b3e25
Revises: 
Create Date: 2025-08-03 16:46:48.585116

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ccb8b01b3e25'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bet', schema=None) as batch_op:
        batch_op.add_column(sa.Column('resolved_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('winning_option_id', sa.Integer(), nullable=True))
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
        batch_op.create_foreign_key(None, 'bet_option', ['winning_option_id'], ['id'])

    with op.batch_alter_table('bet_option', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_winner', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bet_option', schema=None) as batch_op:
        batch_op.drop_column('is_winner')

    with op.batch_alter_table('bet', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
        batch_op.drop_column('winning_option_id')
        batch_op.drop_column('resolved_at')

    # ### end Alembic commands ###
