"""empty message

Revision ID: eb95f6c88061
Revises: 346ca14ea3bb
Create Date: 2025-07-31 17:40:50.295587

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb95f6c88061'
down_revision = '346ca14ea3bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_bet', schema=None) as batch_op:
        batch_op.drop_constraint('user_bet_bet_id_fkey', type_='foreignkey')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_bet', schema=None) as batch_op:
        batch_op.create_foreign_key('user_bet_bet_id_fkey', 'bet', ['bet_id'], ['id'])

    # ### end Alembic commands ###
